on: 
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  build:
    name: Install yarn dependencies and build site package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Upload artifact for S3/CloudFront
        id: deployment
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
  cloudfront:
    needs: build 
    name: Deploy to Cloudfront
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to s3 bucket
        run: aws s3 sync ./build s3://${{ secrets.AWS_MAJESTIC_FRONTEND_BUCKET }}/

      - name: Invalidate cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_MAJESTIC_CLOUDFRONT_DIST }} --paths "/*"
  publish:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
